### ISSUE TITLE
建议合并IP段

### ISSUE THREAD

**Issue by liudongmiao** [fivesheep/chnroutes#23]
本人项目：https://github.com/liudongmiao/chinaip

作为对比，可以极大提高效率，以Fri, 01 Aug 2014 15:15:44 GMT发布的项目为例

以Fri, 01 Aug 2014 15:15:44 GMT的delegated-apnic-latest为例
(以下自动添加3个私有网段)
/14, 376, 86%
/15, 543, 93%
/16, 757, 97%
/17, 856, 98%
/18, 947, 98%
/19, 1114, 99%
.............
/24, 3037, 100%
不合并的话，共4133 + 3个路由，需要更多的1099条路由..

就以实际情况来看，我一个使用/16的方案，覆盖中国97%的ip段

**Comment by fbi007130** [comment]
目测上去有n多个ip段都能合并了，建议合并
